const categories = {}

categories.all = [
    {name: 'House & Garden', attributes: ['condition', 'brand_home', 'responsible']},
    {name: 'Electronics', attributes: ['condition', 'brand_electronics', 'responsible']},
    {name: 'Entertainment', attributes: ['condition']},
    {name: 'Fashion', attributes: ['condition', 'brand_fashion', 'responsible', 'gender']},
    {name: 'Sports & Leisure', attributes: ['condition', 'responsible']},
    {name: 'Health & Beauty', attributes: ['condition', 'brand_health-beauty', 'responsible']},
    {name: 'Toys', attributes: ['condition', 'brand_toys', 'responsible']},
    {name: 'Motors', attributes: ['condition', 'brand_motors', 'responsible']},
    {name: 'Collectables', attributes: ['condition', 'brand_motor-parts', 'responsible']}
]

categories.houseGarden = [
    {name: 'Baby Essentials', parent: 'House & Garden', sub: [
        {name: 'Baby Bathing & Grooming'},
        {name: 'Baby Books'},
        {name: 'Baby Carriers & Backpacks', attributes: ['material_fabric', 'colour', 'brand_fashion']},
        {name: 'Baby Changing & Nappies', attributes: ['size_nappies']},
        {name: 'Baby Feeding'},
        {name: 'Car Seats & Accessories', attributes: ['material_fabric', 'material_plastic', 'material_metal']},
        {name: 'Christening & Gifts'},
        {name: 'Maternity/Pregnancy'},
        {name: 'Nursery Bedding', attributes: ['colour', 'material_fabric']},
        {name: 'Nursery Decoration & Furniture', attributes: ['colour', 'material_fabric', 'material_plastic', 'material_wood', 'material_metal']},
        {name: 'Other Baby'},
        {name: 'Potty Training'},
        {name: 'Pushchairs, Prams & Accessories', attributes: ['colour', 'material_fabric', 'material_metal', 'material_plastic']},
        {name: 'Safety'},
        {name: 'Toys & Activities', attributes: ['colour', 'brand_toys', 'material_plastic', 'material_wood', 'material_rubber', 'material_fabric']},
        {name: 'Walkers'}
    ]},
    {name: 'Celebration & Occasion Supplies', parent: 'House & Garden', sub: [
        {name: 'Cards & Invitations', attributes: ['material_paper']},
        {name: 'Seasonal Decorations', attributes: ['colour']},
        {name: 'Fresh Flowers'},
        {name: 'Gift Baskets'},
        {name: 'Gift Wrapping & Supplies', attributes: ['colour']},
        {name: 'Party Supplies'},
        {name: 'Other Celebrations & Occasions'}
    ]},
    {name: 'Garden & Patio', parent: 'House & Garden', sub: [
        {name: 'Bird & Wildlife', attributes: ['animal_birds', 'material_wood', 'material_stone']},
        {name: 'Composting & Garden'},
        {name: 'Décor', attributes: ['colour']},
        {name: 'Garden Furniture', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic']},
        {name: 'Garden Clothing & Protective Gear', attributes: ['colour', 'material_fabric']},
        {name: 'Garden Fencing, Privacy Screens & Gates', attributes: ['colour', 'material_wood', 'material_stone', 'material_metal']},
        {name: 'Garden Hand Tools', attributes: ['material_metal', 'material_plastic']},
        {name: 'Garden Lighting'},
        {name: 'Garden Power Tools'},
        {name: 'Garden Structures & Shade', attributes: ['material_stone', 'material_metal', 'material_wood']},
        {name: 'Landscaping Materials'},
        {name: 'Lawn Mowers, Parts & Accessories'},
        {name: 'Other Garden & Patio', attributes: ['material_stone']},
        {name: 'Outdoor Heating, Cooking & Eating'},
        {name: 'Plant Care, Soil & Accessories'},
        {name: 'Plants, Seeds & Bulbs'},
        {name: 'Ponds & Water Features', attributes: ['material_stone', 'material_metal', 'material_plastic']},
        {name: 'Swimming Pools, Saunas & Hot Tubs'},
        {name: 'Watering Equipment'},
        {name: 'Weed & Pest Control'}
    ]},
    {name: 'Pet Supplies', parent: 'House & Garden', sub: [
        {name: 'Birds'},
        {name: 'Cats'},
        {name: 'Dogs'},
        {name: 'Fish & Aquarium'},
        {name: 'Other Pet Supplies'},
        {name: 'Pet Memorials'},
        {name: 'Poultry & Waterfowl'},
        {name: 'Reptiles'},
        {name: 'Small Animal Supplies'},
        {name: 'Spiders & Insets'},
        {name: 'Trackers'}
    ]},
    {name: 'Bathroom Fixtures & Accessories', parent: 'House & Garden', sub: [
        {name: 'Bath', attributes: ['material_ceramic', 'material_stone', 'material_plastic', 'colour']},
        {name: 'Bathroom Accessories'},
        {name: 'Bathroom Cabinets', attributes: ['material_wood', 'material_plastic', 'material_metal']},
        {name: 'Bathroom Cladding Panels', attributes: ['material_wood', 'material_stone', 'material_ceramic']},
        {name: 'Bathroom Sinks & Accessories', attributes: ['material_ceramic', 'material_stone', 'material_plastic']},
        {name: 'Bathroom Suites'},
        {name: 'Shows, Baths & Parts'},
        {name: 'Steam Showers'},
        {name: 'Toilets & Bidets', attributes: ['material_ceramic', 'material_stone', 'material_plastic']}
    ]},
    {name: 'Home Furniture', parent: 'House & Garden', sub: [
        {name: 'Beds', attributes: ['colour', 'size_bed', 'material_wood', 'material_metal']},
        {name: 'Bookcases, Shelving & Storage', attributes: ['colour', 'material_wood']},
        {name: 'Cabinets & Sideboards', attributes: ['colour', 'material_wood']},
        {name: 'Chairs', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic']},
        {name: 'Drawers', attributes: ['colour', 'material_wood']},
        {name: 'Home Office Furniture', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic', 'material_ceramic']},
        {name: 'Matresses', attributes: ['colour', 'material_fabric']},
        {name: 'Sofas, Armchairs & Couches', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic', 'material_fabric']},
        {name: 'Tables', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic', 'material_ceramic']},
        {name: 'TV Stands & Entertainment Units', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic', 'material_ceramic']},
        {name: 'Wardrobes', attributes: ['colour', 'material_wood']}
    ]},
    {name: 'DIY Tools & Workshop Equipment', parent: 'House & Garden', sub: [
        {name: 'Air Tools & Compressors'},
        {name: 'Power Tools'},
        {name: 'Air & Power Tool Accessories'},
        {name: 'Air & Power Tool Parts'},
        {name: 'Hand Tools'},
        {name: 'Hand Tool Accessories'},
        {name: 'Hand Tool Parts'},
        {name: 'Measuring & Layout Tools'},
        {name: 'Safety Gear'},
        {name: 'Tool Boxes & Storage'},
        {name: 'Workshop Equipments'},
        {name: 'Other DIY Tools & Workshop'}
    ]},
    {name: 'Household Accessories & Supplies', parent: 'House & Garden', sub: [
        {name: 'Luggage & Travel Accessories'},
        {name: 'Metaphysical & New Age Products'},
        {name: "Children's Furniture & Home Supplies", attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic']},
        {name: 'Other Home, Furniture & DIY', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic']},
        {name: 'Rugs & Carpets', attributes: ['colour', 'material_fabric']},
        {name: 'Smart Home & Survellance'},
        {name: 'Stationary & School Equipment'},
        {name: 'Wedding Supplies'},
        {name: 'Clocks', attributes: ['colour']},
        {name: 'Home Conservatories'},
        {name: 'DIY Materials', attributes: ['colour', 'material_metal', 'material_wood', 'material_plastic', 'material_ceramic', 'material_paper', 'material_rubber', 'material_stone']},
        {name: 'Home Cookware, Dining & Bar Supplies'},
        {name: 'Window Curtains, Blinds & Accessories', attributes: ['colour', 'material_fabric']},
        {name: 'Home Heating, Cooling & Air'}
    ]},
    {name: 'Home Bedding', parent: 'House & Garden', attributes: ['colour', 'material_fabric'], sub: [
        {name: 'Bedding', attributes: ['size_bed']},
        {name: 'Bedding Sets & Duvet Covers', attributes: ['size_bed']},
        {name: 'Blankets'},
        {name: 'Canopies & Netting'},
        {name: 'Decorative Quilts & Bedspreads', attributes: ['size_bed']},
        {name: 'Duvets', attributes: ['size_bed']},
        {name: 'Mattress Toppers & Protectors', attributes: ['size_bed']},
        {name: 'Pillow Cases'},
        {name: 'Pillows'},
        {name: 'Sheets', attributes: ['size_bed']},
        {name: 'Valances'},
        {name: 'Other Bedding'}
    ]}
]

categories.electronics = [
    {name: 'Sound & Vision', parent: 'Electronics', sub: [
        {name: 'DVD, Blu-ray & Home Cinema'},
        {name: 'Headphones', attributes: ['colour']},
        {name: 'Home Audio & HiFi'},
        {name: 'iPod & MP3 Players', attributes: ['colour']},
        {name: 'iPod & MP3 Player Accessories'},
        {name: 'Batteries & Power Supplies'},
        {name: 'Other Sound & Vision'},
        {name: 'Performance & DJ Equipments'},
        {name: 'Portable Radio & Disc Players'},
        {name: 'Smart Glasses', attributes: ['colour']},
        {name: 'TV & Home Audio Accessories'},
        {name: 'TV & Home Audio Parts'},
        {name: 'TV Reception & Set Top Boxes'},
        {name: 'TVs', attributes: ['size_tv-monitor-screen', 'screen-resolution']},
        {name: 'Vintage Sound & Vision'},
        {name: 'Virtual Reality'}
    ]},
    {name: 'Computers, Tablets & Network Hardware', parent: 'Electronics', sub: [
        {name: '3D Printers & Supplies'},
        {name: 'Computer Cables & Connectors'},
        {name: 'Computer Components & Parts', sub: [
            {name: 'RAM', attributes: ['memory']},
            {name: 'Motherboards', attributes: ['motherboard-form-factor']},
            {name: 'CPUs', attributes: ['cpu-speed']},
            {name: 'Graphics Cards', attributes: ['graphics']},
            {name: 'Power Supplies', attributes: ['power-supply']},
        ]},
        {name: 'Computer Drives & Storage', attributes: ['hard-drive']},
        {name: 'Computer Keyboards, Mice & Pointers'},
        {name: 'Computer Monitors', attributes: ['size_tv-monitor-screen', 'screen-resolution']},
        {name: 'Computer Power Protection & Distribution'},
        {name: 'Computer Projectors & Accessories'},
        {name: 'Printers, Scanners & Supplies'},
        {name: 'Computer Sofware'},
        {name: 'Desktops', attributes: ['hard-drive', 'memory', 'motherboard-form-factor', 'cpu-speed', 'graphics', 'power-supply']},
        {name: 'Enterprise & Networking Servers'},
        {name: 'Home Networking & Connectivity'},
        {name: 'Desktop & Laptop Accessories'},
        {name: 'Laptops & Netbooks', attributes: ['hard-drive', 'memory', 'motherboard-form-factor', 'cpu-speed', 'graphics', 'power-supply', 'screen-resolution']},
        {name: 'Other Computers, Tablets & Network Hardware'},
        {name: 'Tablet & eBook Reader Accessories'},
        {name: 'Tablet & eBook Reader Parts'},
        {name: 'Tablets & eBook Readers', attributes: ['size_tablet-phone-screen', 'screen-resolution', 'hard-drive', 'memory', 'motherboard-form-factor', 'cpu-speed', 'graphics', 'size_tv-monitor-screen', 'power-supply']},
        {name: 'Vintage Computing'}
    ]},
    {name: 'Mobile Phones, Smart Watches & Communication', parent: 'Electronics', sub: [
        {name: 'Communication Accessories'},
        {name: 'Dummy Mobile Phones'},
        {name: 'Home Phones & Accessories'},
        {name: 'Mobile & Smart Phones', attributes: ['size_tablet-phone-screen', 'hard-drive', 'memory', 'motherboard-form-factor', 'cpu-speed', 'graphics', 'power-supply']},
        {name: 'Mobile Phones & PDA Accessories'},
        {name: 'Mobile Phone Parts'},
        {name: 'Mobile Phones Software'},
        {name: 'Mobile Phone SIM Cards & Readers'},
        {name: 'Other Phones'},
        {name: 'PDAs', attributes: ['size_tablet-phone-screen', 'screen-resolution', 'hard-drive', 'memory', 'motherboard-form-factor', 'cpu-speed', 'graphics', 'power-supply']},
        {name: 'Radio Communication Equipment'},
        {name: 'Smartwatch Accessories'},
        {name: 'Smartwatches'},
        {name: 'Vintage Mobile Phones'},
        {name: 'Vintage Home Phones'}
    ]},
    {name: 'Game Consoles', parent: 'Electronics', attributes: ['game-console'], sub: [
        {name: 'Coin Operated Gaming Items'},
        {name: 'Other Game Consoles'},
        {name: 'Prepaid Gaming Cards'},
        {name: 'Video Game Accessories'},
        {name: 'Video Game Consoles', attributes: ['screen-resolution', 'hard-drive', 'memory']},
        {name: 'Video Game Merchandise'},
        {name: 'Video Game Replacement Parts & Tools'},
        {name: 'Video Game Strategy & Cheat Guides'}
    ]},
    {name: 'Cameras, Photography & Videography', parent: 'Electronics', sub: [
        {name: 'Camcorders'},
        {name: 'Camera & Camera-Ready Drones'},
        {name: 'Camera & Photo Accessories'},
        {name: 'Camera Drone Parts & Accessories'},
        {name: 'Camera Flashes & Accessories'},
        {name: 'Camera Lenses & Filters'},
        {name: 'Camera Replacement Parts & Tools'},
        {name: 'Camera Tripods & Supports'},
        {name: 'Digital Cameras', attributes: ['screen-resolution']},
        {name: 'Digital Photo Frames', attributes: ['screen-resolution', 'size_tv-monitor-screen', 'size_tablet-phone-screen']},
        {name: 'Film Photography Equipment'}
    ]},
    {name: 'Home Appliances', parent: 'Electronics', sub: [
        {name: 'Coffee, Tea & Espresso'},
        {name: 'Cookers, Ovens & Hobs'},
        {name: 'Dishwashing'},
        {name: 'Fridges & Freezers'},
        {name: 'Ironing & Vacuuming'},
        {name: 'Small Kitchen Appliances'},
        {name: 'Washing Machines & Dryers'},
        {name: 'Other Appliances'}
    ]}
]

categories.entertainment = [
    {name: 'Books, Comics & Magazines', parent: 'Entertainment', sub: [
        {name: 'Book, Comic & Magazine Accessories'},
        {name: 'Antiquarian & Collectable'},
        {name: 'Audio Books'},
        {name: 'Books'},
        {name: 'Catalogues'},
        {name: 'Comic Books & Memorabilia'},
        {name: 'Magazines'},
        {name: 'Textbooks'}
    ]},
    {name: 'Film & TV', parent: 'Entertainment', sub: [
        {name: 'DVDs, Blu-rays & Digital'},
        {name: 'Film Memorabilia'},
        {name: "Film NFT's"},
        {name: 'Film Stock'},
        {name: 'Laser Discs'},
        {name: 'Other Video Formats'},
        {name: 'TV Memorabilia'},
        {name: 'UMDs'},
        {name: 'VHS Tapes'},
        {name: 'Video Media Accessories'}
    ]},
    {name: 'Music', parent: 'Entertainment', sub: [
        {name: 'Audio Media Accessories'},
        {name: 'Cassettes'},
        {name: 'CDs'},
        {name: 'Digital'},
        {name: 'Music Memorabilia'},
        {name: "Music NFT's"},
        {name: 'Other Audio Formats'},
        {name: 'Vinyl Records'}
    ]},
    {name: 'Video Games', parent: 'Entertainment', attributes: ['game-console']}
]

categories.fashion = [
    {name: 'Dresses', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'style_dresses', 'type_dresses', ]},
    {name: 'Hoodies & Sweatshirts', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'style_sweatshirts', 'type_sweatshirts']},
    {name: 'Jackets & Coats', parent: 'Fashion', attributes: ['chest', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_jackets', 'type_jackets']},
    {name: 'Jeans', parent: 'Fashion', attributes: ['waist', 'inner-leg', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_jeans']},
    {name: 'Tracksuits & Joggers', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_tracksuits', 'type_tracksuits']},
    {name: 'Jumpsuits & Playsuits', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children','colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'type_jumpsuits']},
    {name: 'Dungerees', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'type_dungeress']},
    {name: 'Jumpers & Cardigans', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'style_jumpers', 'type_jumpers']},
    {name: 'Lingerie & Nightwear', parent: 'Fashion', attributes: ['band', 'cup', 'size_women','colour', 'bodyfit', 'pattern', 'material_fabric', 'style_lingerie', 'type_lingerie']},
    {name: 'Pyjamas', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'type_pyjamas']},
    {name: 'Loungewear', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'style_loungewear', 'type_loungewear']},
    {name: 'Polo Shirts', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_polos']},
    {name: 'Shirts', parent: 'Fashion', attributes: ['neck', 'chest', 'size_universal', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_shirts', 'type_shirts']},
    {name: 'Leggings & Tights', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_tights', 'type_tights']},
    {name: 'Shorts', parent: 'Fashion', attributes: ['waist', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_shorts', 'type_shorts']},
    {name: 'Socks', parent: 'Fashion', attributes: ['size_adult-shoes', 'size_baby-shoes', 'size_children-shoes', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'type_socks']},
    {name: 'Activewear', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'type_activewear']},
    {name: 'Skirts', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_skirts', 'type_skirts']},
    {name: 'Suits & Tailoring', parent: 'Fashion', attributes: ['waist', 'inner-leg', 'chest', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_suits', 'type_suits']},
    {name: 'Swimwear', parent: 'Fashion', attributes: ['band', 'cup', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'type_swimwear']},
    {name: 'T-Shirts & Vests', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'neckline', 'bodyfit', 'pattern', 'material_fabric', 'style_tshirts', 'type_tshirts']},
    {name: 'Trousers & Chinos', parent: 'Fashion', attributes: ['waist', 'inner-leg', 'size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'style_bottoms', 'type_bottoms']},
    {name: 'Underwear', parent: 'Fashion', attributes: ['size_universal', 'size_women', 'size_baby', 'size_children', 'colour', 'bodyfit', 'pattern', 'material_fabric', 'type_underwear']},
    {name: 'Footwear', parent: 'Fashion', attributes: ['size_adult-shoes', 'size_baby-shoes', 'size_children-shoes', 'colour', 'pattern', 'material_fabric', 'style_footwear', 'type_footwear']},
    {name: 'Accessories', parent: 'Fashion', attributes: ['size_universal', 'size_ankle', 'size_wrist', 'size_finger', 'colour', 'pattern', 'material_fabric', 'material_plastic', 'type_accessories']},
    {name: 'Jewellery', parent: 'Fashion', attributes: ['size_universal', 'size_ankle', 'size_wrist', 'size_finger', 'material_metal', 'material_rubber', 'material_plastic', 'material_wood', 'material_stone', 'precious-stones', 'type_jewellery']}
]

categories.sportsLeisure = [
    {name: 'Arts & Crafts', parent: 'Sports & Leisure', attributes: ['brand_art-materials'], sub: [
        {name: 'Art Supplies', attributes: ['colour']},
        {name: 'Basketry & Chair Caning'},
        {name: 'Beads & Jewellery Making', attributes: ['colour', 'precious-stones']},
        {name: 'Childrens Crafts', attributes: ['colour']},
        {name: 'Decorative & Folk Painting', attributes: ['colour']},
        {name: 'Fabric', attributes: ['colour', 'material_fabric']},
        {name: 'Fabric Painting & Decorating', attributes: ['colour']},
        {name: 'Floral Crafts', attributes: ['colour']},
        {name: 'Framing & Matting', attributes: ['colour', 'material_wood', 'material_metal', 'material_plastic', 'material_ceramic', 'material_stone']},
        {name: 'Glass Art Supplies', attributes: ['colour']},
        {name: 'Hand-Crafted Items', attributes: ['colour']},
        {name: 'Leather Crafts', attributes: ['colour']},
        {name: 'More Crafts', attributes: ['colour']},
        {name: 'Mosaic', attributes: ['colour', 'material_ceramic']},
        {name: 'Multi-Purpose Craft Supplies', attributes: ['colour']},
        {name: 'Needlecraft & Yarn', attributes: ['colour', 'material_fabric']},
        {name: 'Rubber Stamping', attributes: ['colour', 'material_rubber']},
        {name: 'Scrapbooking & Paper', attributes: ['colour', 'material_paper']},
        {name: 'Sculpting, Moulding & Ceramics', attributes: ['colour', 'material_stone', 'material_ceramic']},
        {name: 'Sewing', attributes: ['colour', 'material_fabric']},
        {name: 'Woodworking', attributes: ['colour', 'material_wood']}
    ]},
    {name: 'Musical Instrumets & Pro Audio', parent: 'Sports & Leisure', attributes: ['brand_music-audio'], sub: [
        {name: 'General Music Accessories & Equipment'},
        {name: 'Brass'},
        {name: 'DJ Equipment'},
        {name: 'Guitars & Basses', attributes: ['colour', 'material_wood']},
        {name: 'Instruction Books & Media'},
        {name: 'Karaoke'},
        {name: 'Other Musical Instruments'},
        {name: 'Percussion', attributes: ['colour', 'material_wood', 'material_plastic', 'material_metal']},
        {name: 'Pianos, Keys & Organs'},
        {name: 'Pro Audio Equipment'},
        {name: 'Sheet Music & Song Books'},
        {name: 'Stage Lighting & Effects'},
        {name: 'String'},
        {name: 'Vintage Musical Instruments'},
        {name: 'Wind & Woodwind'}
    ]},
    {name: 'Sporting Goods', parent: 'Sports & Leisure', attributes: ['brand_sports'], sub: [
        {name: 'American Football'},
        {name: 'Archery'},
        {name: 'Badminton'},
        {name: 'Baseball'},
        {name: 'Basketball'},
        {name: 'Bowling'},
        {name: 'Bowls'},
        {name: 'Boxing'},
        {name: 'Camping & Hiking'},
        {name: 'Canoeing & Kayaking'},
        {name: 'Cheerleading'},
        {name: 'Climbing & Mountaineering'},
        {name: 'Coach & Referee Equipment'},
        {name: 'Cricket'},
        {name: 'Curling'},
        {name: 'Cycling'},
        {name: 'Darts'},
        {name: 'Disc Golf'},
        {name: 'Equestrian'},
        {name: 'Field, Ice & Roller Hockey'},
        {name: 'Fishing'},
        {name: 'Fitness, Running & Yoga'},
        {name: 'Football'},
        {name: 'Football Shirts'},
        {name: 'Geocaching'},
        {name: 'Golf'},
        {name: 'Gymnastics'},
        {name: 'Handball'},
        {name: 'Hunting'},
        {name: 'Inline & Roller Skating'},
        {name: 'Kitesurfing & Powerkites'},
        {name: 'Lacrosse'},
        {name: 'Martial Arts'},
        {name: 'More Sporting Goods'},
        {name: 'Paintball'},
        {name: 'Rugby'},
        {name: 'Sailing'},
        {name: 'Scuba & Snorkelling'},
        {name: 'Skateboarding'},
        {name: 'Skydiving, Para & Hand Gliding'},
        {name: 'Snooker & Pool'},
        {name: 'Sport Awards'},
        {name: 'Squash'},
        {name: 'Surfing'},
        {name: 'Swimming'},
        {name: 'Tables Tennis'},
        {name: 'Tennis'},
        {name: 'Volleyball'},
        {name: 'Waterskiing & Wakeboarding'},
        {name: 'Windsurfing'},
        {name: 'Winter Sports'},
        {name: 'Wrestling'}
    ]},
    {name: 'Holidays & Travel', parent: 'Sports & Leisure', sub: [
        {name: 'Accomodation'},
        {name: 'Bus & Coach Tickets'},
        {name: 'Car Rental'},
        {name: 'Ferry & Cruise Tickets'},
        {name: 'Flight Tickets'},
        {name: 'Other Travel'},
        {name: 'Package Holidays'},
        {name: 'Short Breaks'},
        {name: 'Train Tickets'}
    ]},
    {name: 'Events Tickets', parent: 'Sports & Leisure', sub: [
        {name: 'Cinema Tickets'},
        {name: 'Comedy Tickets'},
        {name: 'Concert Tickets'},
        {name: 'Experiences'},
        {name: 'Festival Tickets'},
        {name: 'Gift Vouchers'},
        {name: 'Museum Tickets'},
        {name: 'Other Tickets'},
        {name: 'Sport Events'},
        {name: 'Theatre Tickets'},
        {name: 'Theme Park Tickets'}
    ]}
]

categories.healthBeauty = [
    {name: 'Hair Care & Styling', parent: 'Health & Beauty', sub: [
        {name: 'Bands, Clips & Styling'},
        {name: 'Brushes & Combs'},
        {name: 'Hair Dye & Colourants'},
        {name: 'Hair Extensions & Wigs'},
        {name: 'Hair Loss Treatments'},
        {name: 'Hair Styling Devices'},
        {name: 'Perms'},
        {name: 'Relaxers & Straightening'},
        {name: 'Hair Sets & Kits'},
        {name: 'Shampoo & Conditioner'},
        {name: 'Styling Products'},
        {name: 'Treatments, Oils & Protectors'}
    ]},
    {name: 'Fragrances', parent: 'Health & Beauty', sub: [
        {name: 'Childrens Fragrances'},
        {name: 'Mens Fragrances & Aftershaves'},
        {name: 'Unisex Frangrances'},
        {name: 'Womens Fragrances & Perfume'}
    ]},
    {name: 'Make-Up', parent: 'Health & Beauty', sub: [
        {name: 'Body'},
        {name: 'Eyes'},
        {name: 'Face'},
        {name: 'Lips'},
        {name: 'Make-Up Cases & Bags'},
        {name: 'Make-Up Mixed Lots'},
        {name: 'Make-Up Tools & Accessories'},
        {name: 'Sets & Kits'}
    ]},
    {name: 'Skin Care', parent: 'Health & Beauty', sub: [
        {name: 'Acne & Blemish Treatments'},
        {name: 'Anti-Ageing'},
        {name: 'Blotting Paper'},
        {name: 'Cleansers & Toners'},
        {name: 'Cotton Buds'},
        {name: 'Exfoliators & Scrubs'},
        {name: 'Eye Treatments & Mask'},
        {name: 'Facial Cleansing Device Parts'},
        {name: 'Facial Cleansing Devices'},
        {name: 'Kits & Gift Sets'},
        {name: 'Lightening Creams'},
        {name: 'Lip Balm & Treatments'},
        {name: 'Make-Up Removers'},
        {name: 'Microdermabrasion Tools'},
        {name: 'Moisturisers'},
        {name: 'Night Treatments'},
        {name: 'Skin Masks'},
        {name: 'Skin Peels'}
    ]},
    {name: 'Nail Care', parent: 'Health & Beauty', sub: [
        {name: 'Nail Art'},
        {name: 'Nail Treatments'},
        {name: 'Nail Tools'},
        {name: 'Nail Polish & Powders'},
        {name: 'Nail Polish Removers'},
        {name: 'Nail Practice & Displays'},
        {name: 'Spa & Bath Devices'},
        {name: 'Storage & Empty Containers'}
    ]},
    {name: 'Bath & Body', parent: 'Health & Beauty', sub: [
        {name: 'Bath & Body Kits & Gift Sets'},
        {name: 'Bath Bombs'},
        {name: 'Bath Brushes & Sponges'},
        {name: 'Bath Oils'},
        {name: 'Bath Salts'},
        {name: 'Body Cleansers'},
        {name: 'Body Powders'},
        {name: 'Body Soaps'},
        {name: 'Body Sprays & Mists'},
        {name: 'Bubble Baths'},
        {name: 'Deodorants & Anti-Perspirants'},
        {name: 'Hand Washes'},
        {name: 'Scar & Stretch Mark Reducers'},
        {name: 'Shower Caps'},
        {name: 'Travel Bottles & Containers'}
    ]},
    {name: 'Vapes & Accessories', parent: 'Health & Beauty', sub: [
        {name: 'Vape Accessories'},
        {name: 'Vape Parts'},
        {name: 'Vapes & Mods'},
        {name: 'Vape Liquids & Cartidges'}
    ]},
    {name: 'Health Care', parent: 'Health & Beauty', sub: [
        {name: 'Diabetes Care'},
        {name: 'Ear Care'},
        {name: 'Feminine Care'},
        {name: 'First Aid'},
        {name: 'Foot Creams & Treatments'},
        {name: 'Hot & Cold Therapies'},
        {name: 'Monitoring & Testing'},
        {name: 'Other Health Care'},
        {name: 'Over-The-Counter Medications & Treatments'},
        {name: 'Personal Hygiene'},
        {name: 'Pharmacy Medicines'},
        {name: 'Pill Holders & Boxes'},
        {name: 'Sexual Wellness'},
        {name: 'Sleeping Aids'},
        {name: 'Smoking Cessation'},
        {name: 'Squeezable Stress Relievers'}
    ]},
    {name: 'Massage', parent: 'Health & Beauty', sub: [
        {name: 'Electric Massage Chairs'},
        {name: 'Linens & Covers'},
        {name: 'Massage Oils & Lotions'},
        {name: 'Massage Pillows & Bolsters'},
        {name: 'Massage Stones & Rocks'},
        {name: 'Massage Tables & Chairs'},
        {name: 'Massagers'},
        {name: 'Other Massage'}
    ]},
    {name: 'Medical & Mobility', parent: 'Health & Beauty', sub: [
        {name: 'Daily Living Aids'},
        {name: 'Mobility Furniture & Fixtures'},
        {name: 'Mobility & Walking Equipment'},
        {name: 'Orthopardics & Support'}
    ]},
    {name: 'Natural & Alternative Remedies', parent: 'Health & Beauty', sub: [
        {name: 'Acupressure'},
        {name: 'Acupuncture'},
        {name: 'Aromatherapy'},
        {name: 'CBD Products'},
        {name: 'Detox Pads'},
        {name: 'Electrotherapy'},
        {name: 'Herbal Remedies & Resin'},
        {name: 'Homeopathic Remedies'},
        {name: 'Ion Foot Baths'},
        {name: 'Light Therapy'},
        {name: 'Magnetic Therapy'},
        {name: 'Neti Pots & Cleansers'},
        {name: 'Other Natural Remdies'},
        {name: 'Self Help Audiovisuals'},
        {name: 'Titanium Therapy'},
        {name: 'Vacuum Suction & Cupping Therapy'},
        {name: 'Vaporizers'}
    ]},
    {name: 'Oral Care', parent: 'Health & Beauty', sub: [
        {name: 'Breath Fresheners'},
        {name: 'Dental Floss'},
        {name: 'Dental Guards'},
        {name: 'Denture Care'},
        {name: 'Electric Oral & Dental Care'},
        {name: 'Manual Toothbrushes'},
        {name: 'Mouthwash'},
        {name: 'Orthopedic Care'},
        {name: 'Teeth Whitening'},
        {name: 'Teehing Pain Relief'},
        {name: 'Temporary Teeth & Supplies'},
        {name: 'Tongue Cleansers'},
        {name: 'Toothpaste'}
    ]},
    {name: 'Other Health & Beauty', parent: 'Health & Beauty'},
    {name: 'Salon & Spa', parent: 'Health & Beauty', sub: [
        {name: 'Backwash Units & Shampoo Bowls'},
        {name: 'Capes & Gowns'},
        {name: 'Hair & Make-Up Mannequins'},
        {name: 'Magnifying Lamps'},
        {name: 'Professional Facial Machines'},
        {name: 'Rolling Cosmetic Boxes'},
        {name: 'Salon & Spa Supplies'},
        {name: 'Salon Dryers & Steamers'},
        {name: 'Scissors & Shears'},
        {name: 'Stylist Stations & Furniture'},
        {name: 'Towel Warmers & Sterilisers'},
        {name: 'Wax Heaters'}
    ]},
    {name: 'Shaving & Hair Removal', parent: 'Health & Beauty', sub: [
        {name: 'Electric Shaving & Hair Removal'},
        {name: 'Hair Removal Creams & Sprays'},
        {name: 'Hair Removal Wax'},
        {name: 'Razors & Razor Blades'},
        {name: 'Shaving & Grooming Kits'},
        {name: 'Shaving Brushes & Mugs'},
        {name: 'Shaving Creams, Foams & Gels'},
        {name: 'Tweezers'},
        {name: 'Waxing Supplies'}
    ]},
    {name: 'Sun Care & Tanning', parent: 'Health & Beauty', sub: [
        {name: 'After Sun Skin Care'},
        {name: 'Airbrush Tanning Compressors'},
        {name: 'Airbrush Tanning Parts'},
        {name: 'Airbrush Tanning Solutions'},
        {name: 'Airbrush Tanning Systems & Kits'},
        {name: 'Airbrush Tents'},
        {name: 'Fake Tanning Products'},
        {name: 'Sun Bed & Booth Parts'},
        {name: 'Sun Beds & Booths'},
        {name: 'Sunscreens & Sunblocks'},
        {name: 'Tanning Body Stickers'},
        {name: 'Tanning Disposables'},
        {name: 'Tanning Lotions'}
    ]},
    {name: 'Tattoos & Body Art', parent: 'Health & Beauty', sub: [
        {name: 'Numbing Creams & Aftercare'},
        {name: 'Other Tattoos & Body Art'},
        {name: 'Piercing Kits'},
        {name: 'Piercing Supplies'},
        {name: 'Tattoo Complete Kits'},
        {name: 'Tattoo Grips'},
        {name: 'Tattoo Machine Parts'},
        {name: 'Tattoo Machines'},
        {name: 'Tattoo Needles'},
        {name: 'Tattoo Removal Machines'},
        {name: 'Tattoo Supplies'},
        {name: 'Tattoo Tips'},
        {name: 'Temporary Tattoos'}
    ]},
    {name: 'Vision Care', parent: 'Health & Beauty', sub: [
        {name: 'Contact Lens Care Solutions'},
        {name: 'Contact Lens Storage & Equipment'},
        {name: 'Eye Drops & Wash'},
        {name: 'Eyeglass Repair'},
        {name: 'Eyeglasses Parts'},
        {name: 'Eyepatches & Glasses Patches'},
        {name: 'Glasses Cases & Storage'},
        {name: 'Glasses Cleaning Tools & Supplies'},
        {name: 'Glasses Frames'},
        {name: 'Glasses Straps, Cords & Grips'},
        {name: 'Low Vision Magnifiers'},
        {name: 'Reading Glasses'},
        {name: 'Replacement Lenses'},
        {name: 'Sppecial Purpose Glasses'}
    ]},
    {name: 'Vitamins & Lifestyle Supplements', parent: 'Health & Beauty', sub: [
        {name: 'Dietary Supplement Accessories'},
        {name: 'Dietary Supplements'},
        {name: 'Endurance & Energy Bars'},
        {name: 'Other Vitamins & Supplements'},
        {name: 'Sports Supplements'},
        {name: 'Vitamins & Minerals'},
        {name: 'Weight Management'}
    ]}
]

categories.toys = [
    {name: 'Action Toys', parent: 'Toys', sub: [
        {name: 'Action Figures'},
        {name: 'Action Figure Accessories'},
        {name: 'Action Figure Parts'},
        {name: 'Action Figure Playsets'},
        {name: 'Action Figure Supplies & Storage'},
        {name: 'Action Figure Mixed Lots'}
    ]},
    {name: 'Beanies', parent: 'Toys', sub: [
        {name: 'Beanie Accessories'},
        {name: 'Bammers & Bamm Beanos'},
        {name: 'Bean Bag Plush'},
        {name: 'Other Beanies'},
        {name: 'Ty Attic'},
        {name: 'Ty Beanie Babies'},
        {name: 'Ty Beanie Boppers'},
        {name: 'Ty Beanie Buddies'},
        {name: 'Ty Beanie Kids'},
        {name: 'Ty Beanie Pals'},
        {name: 'Ty Plush'},
        {name: 'Ty Teenie Beanies'}
    ]},
    {name: 'Construction & Building Toys', parent: 'Toys', sub: [
        {name: 'Construction Toy Accessories'},
        {name: 'Construction Toy Minifigures'},
        {name: 'Construction Toy Pieces'},
        {name: 'Construction Toy Sets & Packs'},
        {name: "K'NEX Building Toys"},
        {name: 'LEGO Building Toys'},
        {name: 'Mega Bloks Building Toys'}
    ]},
    {name: 'Creative Toys', parent: 'Toys'},
    {name: 'Diecast & Vehicles', parent: 'Toys', sub: [
        {name: 'Accessories, Parts & Displays'},
        {name: 'Aircraft & Spacecraft'},
        {name: 'Boats & Ships'},
        {name: 'Cars, Trucks & Vans'},
        {name: 'Collections & Bulk Lots'},
        {name: 'Construction Equipment'},
        {name: 'Farm Vehicles'},
        {name: 'Magazines & Other Publications'},
        {name: 'Motorcycles & ATVs'},
        {name: 'Other Vehicles'},
        {name: 'Play Sets'},
        {name: 'Racing Cars'},
        {name: 'Tanks & Military Vehicles'}
    ]},
    {name: 'Educational Toys', parent: 'Toys', sub: [
        {name: 'Alphabet'},
        {name: 'Geography & History'},
        {name: 'LeapFrog & Leapster'},
        {name: 'Mathematics'},
        {name: 'Music & Art'},
        {name: 'Numbers'},
        {name: 'Other Educational Toys'},
        {name: 'Reading & Writing'},
        {name: 'Science & Nature'},
        {name: 'Special Education Needs'},
        {name: 'VTech'}
    ]},
    {name: 'Electronic Pets', parent: 'Toys'},
    {name: 'Fast Food, Cereal & Sweet Toys', parent: 'Toys'},
    {name: 'Games', parent: 'Toys', sub: [
        {name: 'Adult & Drinking Games'},
        {name: 'Air Hockey'},
        {name: 'Board & Traditional Games'},
        {name: 'Chess'},
        {name: 'Electronic Games'},
        {name: 'Executive Toys & Gadgets'},
        {name: 'Game Pieces & Parts'},
        {name: 'Jokes & Pranks'},
        {name: 'Mighty Beanz'},
        {name: 'Other Games'},
        {name: 'Pocket Money Toys & Games'},
        {name: 'Poker & Card Games'}
    ]},
    {name: 'Jigsaws & Puzzles', parent: 'Toys', sub: [
        {name: '3D Puzzles'},
        {name: 'Cube, Twist & Brain Teasers'},
        {name: 'Jigsaws'},
        {name: 'Other Puzzles'},
        {name: 'Vintage Puzzles'}
    ]},
    {name: 'Models & Kits', parent: 'Toys', sub: [
        {name: 'Aircraft'},
        {name: 'Automotive'},
        {name: 'Model Boats & Ships'},
        {name: 'Buildings'},
        {name: 'Dioramas'},
        {name: 'Figures'},
        {name: 'Other Models & Kits'},
        {name: 'Price Guides & Publications'},
        {name: 'Spacecraft'},
        {name: 'Tools, Supplies & Engines'}
    ]},
    {name: 'Other Toys', parent: 'Toys'},
    {name: 'Outdoor Toys', parent: 'Toys', sub: [
        {name: 'Boomerangs'},
        {name: 'Boules & Petanque'},
        {name: 'Bouncy Castles & Inflatables'},
        {name: 'Climbing Frames'},
        {name: 'Croquet'},
        {name: 'Floats & Rafts'},
        {name: 'Flying Discs'},
        {name: 'Garden Games & Activities'},
        {name: 'Juggling'},
        {name: 'Kites'},
        {name: 'Other Outdoor Toys'},
        {name: 'Paddling Pools'},
        {name: 'Playhouses'},
        {name: 'Pogo Sticks'},
        {name: 'Pool Toys & Games'},
        {name: 'Ride-On Cars'},
        {name: 'Sand Pits & Toys'},
        {name: 'Scooters'},
        {name: 'Skates'},
        {name: 'Skipping Ropes'},
        {name: 'Slides'},
        {name: 'Space Hoppers'},
        {name: 'Swingball'},
        {name: 'Swings'},
        {name: 'Tents'},
        {name: 'Trampolines'},
        {name: 'Tricycles'},
        {name: 'Water Pistols'}
    ]},
    {name: 'Preschool Toys & Pretend Play', parent: 'Toys', sub: [
        {name: 'Brio'},
        {name: 'Chicco'},
        {name: 'Early Learning Centre'},
        {name: 'Fisher Price & Little People'},
        {name: 'Little Tikes'},
        {name: 'Other Preschool'},
        {name: 'Playmobil'},
        {name: 'Playskool'},
        {name: 'Pretend Kitchens'},
        {name: 'Pretend Shops'},
        {name: 'Smoby'},
        {name: 'Tomy'},
        {name: 'Unbranded Preschool Toys'},
        {name: 'Vintage Preschool Toys'},
        {name: 'Wooden Toys'}
    ]},
    {name: 'Radio Controlled & RC Toys', parent: 'Toys', sub: [
        {name: 'Control Line & Free Flight'},
        {name: 'Other Radio Controlled & RC Toys'},
        {name: 'RC Model Vehicle Parts'},
        {name: 'RC Model Vehicles & Kits'},
        {name: 'Simulators'},
        {name: 'Tether Cars'}
    ]},
    {name: 'Scalextric & Slot Car', parent: 'Toys', sub: [
        {name: 'Accessories & Tuning'},
        {name: 'Boxed Sets'},
        {name: 'Cars'},
        {name: 'Minic Motorways'},
        {name: 'Other Slot Cars'},
        {name: 'Track'},
        {name: 'Trackside Props & Buildings'}
    ]},
    {name: 'Soft & Stuffed Toys', parent: 'Toys', sub: [
        {name: 'Branded & Soft Toys'},
        {name: 'Disney'},
        {name: 'Other Soft Toys'},
        {name: 'Steiff'},
        {name: 'Unbranded Soft Toys'}
    ]},
    {name: 'Steam Toys', parent: 'Toys'},
    {name: 'Toy Soldiers', parent: 'Toys', sub: [
        {name: 'Airfix'},
        {name: 'Britains'},
        {name: 'Charbens'},
        {name: 'Cherilea'},
        {name: 'Crescent'},
        {name: 'Del Prado'},
        {name: 'Elastolin'},
        {name: 'King & Country'},
        {name: 'Lone Star'},
        {name: 'Other Toy Soliders'},
        {name: 'Timpo'},
        {name: 'Unbranded Toy Soldiers'}
    ]},
    {name: 'Vintage & Classic Toys', parent: 'Toys', sub: [
        {name: 'Bagatelle'},
        {name: 'Battery Operated'},
        {name: 'Clockwork & Wind-Up'},
        {name: 'Etch-a-Sketch'},
        {name: 'Magic, Tricks & Jokes'},
        {name: 'Marbles'},
        {name: 'Optical Toys'},
        {name: 'Other Vintage & Classic Toys'},
        {name: 'Puppets'},
        {name: 'Robots & Space Toys'},
        {name: 'Rocking Horses'},
        {name: 'Slinky'},
        {name: 'Tinplate & Penny Toys'},
        {name: 'Vintage Construction Toys'},
        {name: 'Weebles'},
        {name: 'Yo-Yos'}
    ]},
    {name: 'Wargames & Role Playing', parent: 'Toys', sub: [
        {name: 'Confrontation'},
        {name: 'Herclix'},
        {name: 'Magazines & Publications'},
        {name: 'MechWarrior'},
        {name: 'Other Wargames'},
        {name: 'Pirates'},
        {name: 'Role-Playing'},
        {name: 'Scenery, Props & Paint'},
        {name: 'Star Wars Games'},
        {name: 'Table Top & Historical'},
        {name: 'Warhammer'},
        {name: 'Warmachine'}
    ]}
]

categories.motors = [
    {name: 'Car Parts & Accessories', parent: 'Motors', sub: [
        {name: 'Car Battery Chargers & Conditioners'},
        {name: 'Car Care & Cleaning Products'},
        {name: 'Car Covers & Tarpaulins'},
        {name: 'Car Interior Accessories'},
        {name: 'Car Jacks & Axle Stands'},
        {name: 'Car Learner "L" & "P" Plates'},
        {name: 'Car Safety Accessories'},
        {name: 'Car Security Equipment'},
        {name: 'Car Touring & Travel Accessories'},
        {name: 'Car Trailers & Towing'},
        {name: 'Other Car Accessories'}
    ]},
    {name: 'Car Care & Cleaning', parent: 'Motors', sub: [
        {name: 'Car Air Fresheners'},
        {name: 'Car Bug & Tar Removers'},
        {name: 'Car Glass Care & Water Repellent'},
        {name: 'Car Ice Scrapers & Snow Brushes'},
        {name: 'Car Interior Cleaners & Protectant'},
        {name: 'Car Mitts, Bonnets & Buffing Pads'},
        {name: 'Car Paint Protection Film'},
        {name: 'Car Power Polishers'},
        {name: 'Car Squugees'},
        {name: 'Car Touch-Up Materials'},
        {name: 'Car Wash Soap'},
        {name: 'Car Wash, Wax & Cleaning Kits'},
        {name: 'Car Washing Brushes & Nozzles'},
        {name: 'Car Waxes & Polishes'},
        {name: 'Car Wheel & Tyre Cleaners'},
        {name: 'Vehicle Vacuums'},
        {name: 'Car Air Conditioning & Heating Parts'},
        {name: 'Car Air Intage & Fuel Delivery Parts'},
        {name: 'Car Brakes & Brake Pags'},
        {name: 'Car Electrical Components'},
        {name: 'Car Emission Systems'},
        {name: 'Car Engine Cooling'},
        {name: 'Car Engines & Engine Parts'},
        {name: 'Car Exhausts & Exhaust Parts'},
        {name: 'Car Exterior & Body Parts'},
        {name: 'Car External Lights & Indicators'},
        {name: 'Car Gauges, Dials & Instruments'},
        {name: 'Car Ignition Parts'},
        {name: 'Car Interior Parts & Furnishings'},
        {name: 'Car Service Kits'},
        {name: 'Car Suspension & Steering Parts'},
        {name: 'Car Transmission & Drivetrain Parts'},
        {name: 'Car Turbos & Superchargers'},
        {name: 'Car Windscreen Wiper & Washer Parts'},
        {name: 'Other Car Parts'}
    ]},
    {name: 'Car Tuning & Styling', parent: 'Motors', sub: [
        {name: 'Car Air Intake & Induction Parts'},
        {name: 'Car Body & Exterior Styling Parts'},
        {name: 'Car Engine Tuning & Chips'},
        {name: 'Car Fuel Systems & Injection Parts'},
        {name: 'Car Interior Styling Parts'},
        {name: 'Car Performance Braking Parts'},
        {name: 'Car Performance Cooling Parts'},
        {name: 'Car Performance Exhaust Parts'},
        {name: 'Car Performance Ignition Parts'},
        {name: 'Car Performance Suspension Parts'},
        {name: 'Car Performance Transmission Parts'},
        {name: 'Car Racing Equipment & Accessories'},
        {name: 'Car Tuning Electrical Components'},
        {name: 'Custom Car Lights'},
        {name: 'Go-Kart Lights'},
        {name: 'Other Car Tuning & Styling Parts'}
    ]},
    {name: 'Car Wheels, Tyres & Trims', parent: 'Motors', sub: [
        {name: 'Car Rim Protectors'},
        {name: 'Car Rims'},
        {name: 'Car Snow Chains & Socks'},
        {name: 'Car Spare Wheel Covers'},
        {name: 'Car Spigot Rings'},
        {name: 'Car Tyre Pressure Monitoring Systems'},
        {name: 'Car Tyre Valve Caps & Stems'},
        {name: 'Car Tyres'},
        {name: 'Car Wheel Centre Caps'},
        {name: 'Car Wheel Nuts, Bolts & Studs'},
        {name: 'Car Wheel Spacers'},
        {name: 'Car Wheel Trims'},
        {name: 'Car Wheels With Tyres'}
    ]},
    {name: 'Commercial Vehicle Parts', parent: 'Motors', sub: [
        {name: 'Agricultural Vehicle Parts'},
        {name: 'Commercial Lorry & Truck Parts'},
        {name: 'Commercial Trailer & Transporter Parts'},
        {name: 'Commercial Van & Pickup Parts'},
        {name: 'Minibus. Bus & Coach Parts'},
        {name: 'Other Commercial Vehicle Parts'}
    ]},
    {name: 'Garage Equipment & Tools', parent: 'Motors', sub: [
        {name: 'Vehicle Air Compressors & Inflators'},
        {name: 'Vehicle Air Conditioning Tools'},
        {name: 'Vehicle Air Tools'},
        {name: 'Vehicle Battery Testers & Chargers'},
        {name: 'Vehicle Diagnostic Equipment & Tools'},
        {name: 'Vehicle Hand Tools'},
        {name: 'Vehicle Paints & Supplies'},
        {name: 'Vehicle Power Tools & Equipment'},
        {name: 'Vehicle Repair Tools & Kits'},
        {name: 'Vehicle Tool Boxes & Storage'},
        {name: 'Workshop Equipment & Supplies'}
    ]},
    {name: 'Tech, GPS & Security', parent: 'Motors', sub: [
        {name: 'Car Dash Cams, Alarms & Security Devices'},
        {name: 'Car GPS & Satellite Navigation Systems'},
        {name: 'Car Parking Assistance Devices'},
        {name: 'Car Radios For Parts'},
        {name: 'Car Speaker & Subwoofer Installation Equipment'},
        {name: 'Car Terminals & Wiring'},
        {name: 'In-Car Electronics Accessories'},
        {name: 'In-Car Entertainment Equipment'},
        {name: 'Other Tech, GPS & Security Devices'},
        {name: 'Vintage Car Radios'}
    ]},
    {name: 'Motorcycle Accessories', parent: 'Motors', sub: [
        {name: 'Motorcycle Battery Chargers & Optimisers'},
        {name: 'Motorcycle Car, Cleaning & Protection Supplies'},
        {name: 'Motorcycle Electronics & Navigation Equipment'},
        {name: 'Motorcycle Lifts & Stands'},
        {name: 'Motorcycle Luggage'},
        {name: 'Motocycle Ramps & Towing Equipment'},
        {name: 'Motorcycle Safety & Security Equipment'},
        {name: 'Motorcycle Stickers Emblems & Flags'},
        {name: 'Motorcycle Tax Disc Holders'},
        {name: 'Motorcycle Weather Protection Equipment'},
        {name: 'Other Motorcycle Accessories'}
    ]},
    {name: 'Motorcycle Parts', parent: 'Motors', sub: [
        {name: 'Motorcycle Air Intake & Fuel Delivery Parts'},
        {name: 'Motorcycle Bodywork & Frame Parts'},
        {name: 'Motorcycle Brakes & Brake Parts'},
        {name: 'Motorcycle Crash Protection'},
        {name: 'Motorcycle Dash Display Instuments & Gauges'},
        {name: 'Motorcycle Drivetrain & Transmission Parts'},
        {name: 'Motorcycle Electrical & Ignition Parts'},
        {name: 'Motorcycle Engine Cooling System'},
        {name: 'Motorcycle Engines & Engine Parts'},
        {name: 'Motorcycle Exhausts & Exhaust System Parts'},
        {name: 'Motorcycle Footrests, Pedals & Pegs'},
        {name: 'Motorcycle Handlebars, Grips & Levers'},
        {name: 'Motorcycle Lighting & Indicators'},
        {name: 'Motorcycle Mirrors'},
        {name: 'Motorcycle Seats & Seat Parts'},
        {name: 'Motorcycle Service Kits'},
        {name: 'Motorcycle Suspension & Handling Parts'},
        {name: 'Motorcycle Tuning & Styling Parts'},
        {name: 'Other Motorcycle Parts'}
    ]},
    {name: 'Motorcycle Wheels & Tyres', parent: 'Motors', sub: [
        {name: 'Motorcycle Axles, Bearings & Seals'},
        {name: 'Motocycle Tyre Valve Caps & Stems'},
        {name: 'Motorcycle Tyres & Tubes'},
        {name: 'Motorcycle Wheel Hub Assemblies'},
        {name: 'Motorcycle Wheel Tape & Trims'},
        {name: 'Motorcycle Wheels'},
        {name: 'Motorcycle Wheels With Tyres'},
        {name: 'Other Motorcycle Wheels, Tyres, Tubes & Parts'}
    ]},
    {name: 'Motorhome Parts & Accessories', parent: 'Motors', sub: [
        {name: 'Campervan & Motorhome Parts'},
        {name: 'Caravan Parts'},
        {name: 'Motorhome Accessories'},
        {name: 'Motohome Awnings'},
        {name: 'Other Camper & Caravan Parts'}
    ]},
    {name: 'Vehicle Clothing, Helments & Protection', parent: 'Motors', sub: [
        {name: 'Car & Kart Racewear'},
        {name: 'Motocross & Off-Road Clothing'},
        {name: 'Motorcycle Body Armour & Protectors'},
        {name: 'Motorcycle Clothing'},
        {name: 'Motorcycle Helmets & Headwear'},
        {name: 'Mechanics Wear'},
        {name: 'Other Vehicle Clothing, Helmets & Protection'},
    ]},
    {name: 'Vehicle Oils, Fluids & Lubricants', parent: 'Motors', sub: [
        {name: 'Other Vehicle Oils, Fluids & Lubricants'},
        {name: 'Vehicle Air Conditioning Chemicals'},
        {name: 'Vehicle Antifreeze'},
        {name: 'Vehicle Brake Fluids'},
        {name: 'Vehicle Cleaners & Degreasers'},
        {name: 'Vehicle Clutch Fluids'},
        {name: 'Vehicle De-Icers'},
        {name: 'Vehicle Engine Oils'},
        {name: 'Vehicle Fuel Additives & Treatments'},
        {name: 'Vehicle Gasket Makers, Removers & Sealers'},
        {name: 'Vehicle Gear & Differential Oils'},
        {name: 'Vehicle Greases'},
        {name: 'Vehicle Radiator Additives & Sealants'},
        {name: 'Vehicle Spray Lubricants'},
        {name: 'Vehicle Steering Fluids'},
        {name: 'Vehicle Starting Fluids'},
        {name: 'Vehicle Suspension Fluids'},
        {name: 'Vehicle Transmission Fluids'},
        {name: 'Vehicle Tyre Sealants'},
        {name: 'Vehicle Windscreen Fluid'}
    ]},
    {name: 'Vehicle Parts & Accessories', parent: 'Motors'},
    {name: 'Automotive Essentials', parent: 'Motors'}
]

categories.collectables = [
    {name: 'Antique Clocks', parent: 'Collectables', sub: [
        {name: 'Alarm Clocks & Clock Radios'},
        {name: 'Cuckoo & Black Forest Clocks'},
        {name: 'Desk, Mantel & Shelf Clocks'},
        {name: 'Digital Clocks'},
        {name: 'Grandfather Clocks'},
        {name: 'Wall Clocks'},
        {name: 'Replacement Parts & Tools'},
        {name: 'Other Clocks'}
    ]},
    {name: 'Antique Furniture', parent: 'Collectables', sub: [
        {name: 'Antique Armoires & Wardrobes', attributes: ['colour', 'material_wood']},
        {name: 'Antique Beds & Frames', attributes: ['colour', 'size_bed', 'material_wood', 'material_metal']},
        {name: 'Antique Bedroom Sets', attributes: ['colour', 'size_bed', 'material_fabric']},
        {name: 'Antique Benches & Stools', attributes: ['colour', 'material_wood', 'material_metal']},
        {name: 'Antique Bookcases', attributes: ['colour', 'material_wood']},
        {name: 'Antique Cabinets & Cupboards', attributes: ['colour', 'material_wood']},
        {name: 'Antique Chairs', attributes: ['colour', 'material_wood', 'material_metal']},
        {name: 'Antique Dining Sets'},
        {name: 'Antique Dressers & Drawers', attributes: ['colour', 'material_wood']},
        {name: 'Antique Desks', attributes: ['colour', 'material_wood']},
        {name: 'Antique Hall Trees & Stands'},
        {name: 'Antique Mirrors'},
        {name: 'Antique Nightstands', attributes: ['colour', 'material_wood']},
        {name: 'Antique Ottomans, Footsalls & Poufs', attributes: ['colour', 'material_wood', 'material_fabric']},
        {name: 'Antique Screens & Room Dividers', attributes: ['colour', 'material_wood']},
        {name: 'Antique Sideboards', attributes: ['colour', 'material_wood']},
        {name: 'Antique Sofas & Chaises', attributes: ['colour', 'material_wood', 'material_fabric']},
        {name: 'Antique Tables', attributes: ['colour', 'material_wood']},
        {name: 'Antique Trunk & Chests', attributes: ['colour', 'material_wood']},
        {name: 'Antique Vanities & Vanity Tables', attributes: ['colour', 'material_wood']},
        {name: 'Antique Parts & Salvaged Pieces'},
        {name: 'Other Antique Furniture'}
    ]},
    {name: 'Antique Silver', parent: 'Collectables', sub: [
        {name: 'Antique Silver Plate'},
        {name: 'Antique Solid Silver'}
    ]},
    {name: 'Antiques', parent: 'Collectables', sub: [
        {name: 'Asian & Oriental Antiques'},
        {name: 'Ethnographic Antiques'},
        {name: 'Incunabala'},
        {name: 'Manuscripts'},
        {name: 'Maps, Atlases & Globes'},
        {name: 'Marine & Maritime'},
        {name: 'Metalware'},
        {name: 'Musical Instruments'},
        {name: 'Other Antiques'},
        {name: 'Restoration & Care'},
        {name: 'Antique Rugs & Carpets'},
        {name: 'Science & Medecine'},
        {name: 'Tapestries'},
        {name: 'Woodenware'}
    ]},
    {name: 'Architectural Antiques', parent: 'Collectables', sub: [
        {name: 'Antique Chandeliers, Sconces & Light Fixtures'},
        {name: 'Antique Doors'},
        {name: 'Antique Door Bells & Knockers'},
        {name: 'Antique Fireplaces, Mantels & Fireplace Accessories'},
        {name: 'Antique Garden'},
        {name: 'Antique Hardware'},
        {name: 'Antique Hooks, Brackets & Curtain Rods'},
        {name: 'Antique Light Switches'},
        {name: 'Antique Locks, Latches & Keys'},
        {name: 'Antique Plaques'},
        {name: 'Antique Plumbing & Fixtures'},
        {name: 'Antique Signs'},
        {name: 'Antique Stained Glass Windows'},
        {name: 'Antique Stair & Carpet Rods'},
        {name: 'Antique Tiles'},
        {name: 'Antique Weathervanes & Lightning Rods'},
        {name: 'Antique Windows, Shutters & Sash Locks'},
        {name: 'Antique Other Artchitectural Antiques'}
    ]},
    {name: 'Art', parent: 'Collectables', sub: [
        {name: 'Art Drawings'},
        {name: "Art NFT's"},
        {name: 'Art Photographs'},
        {name: 'Art Posters'},
        {name: 'Art Prints'},
        {name: 'Art Sculptures'},
        {name: 'Mixed Media Art & Collage Art'},
        {name: 'Other Art'},
        {name: 'Paintings'},
        {name: 'Textile & Fiber Art'}
    ]},
    {name: 'Autographs', parent: 'Collectables', sub: [
        {name: 'Certified Original Autographs'},
        {name: 'Uncertified Original Autographs'},
        {name: 'Pre-Printed Autographs'}
    ]},
    {name: 'Badges & Patches', parent: 'Collectables', sub: [
        {name: 'Badges', attributes: ['colour', 'material_fabric']},
        {name: 'Patches', attributes: ['colour', 'material_fabric']}
    ]},
    {name: 'Breweriana', parent: 'Collectables', sub: [
        {name: 'Babycham'},
        {name: 'Guiness'},
        {name: 'Jack Daniels'},
        {name: 'Bar Towels'},
        {name: 'Beer Advertising'},
        {name: 'Beer Ashtrays'},
        {name: 'Beer Badges & Pins'},
        {name: 'Beer Bottles'},
        {name: 'Beer Cans'},
        {name: 'Beer Jugs'},
        {name: 'Beer Mats & Coasters'},
        {name: 'Beer Paper & Labels'},
        {name: 'Beer Signs'},
        {name: 'Beer Tape Handles'},
        {name: 'Beer Trays'},
        {name: 'Bottle Openers'},
        {name: 'Clothing & Hats'},
        {name: 'Novelty Items'},
        {name: 'Corkscrews'},
        {name: 'Decanters'},
        {name: 'Drinkware, Glasses & Steins'},
        {name: 'Hip Flasks'},
        {name: 'Playing Cards'},
        {name: 'Pumps, Clips & Optics'},
        {name: 'Shakers'},
        {name: 'Soda Siphops'},
        {name: 'Other Breweriana'}
    ]},
    {name: 'Carpets & Rugs', parent: 'Collectables', attributes: ['colour', 'material_fabric']},
    {name: 'Coins', parent: 'Collectables', sub: [
        {name: 'Banknotes'},
        {name: 'Bulion & Bars'},
        {name: 'Historical Medals & Medalions'},
        {name: 'Share Certificates & Bonds'},
        {name: 'Tokens'},
        {name: 'Virtual Currency'}
    ]},
    {name: 'Comics', parent: 'Collectables', sub: [
        {name: 'Franco-Belgian & European'},
        {name: 'Manga & Asian Comics'},
        {name: 'Original Comic Art'},
        {name: 'Artbooks'},
        {name: 'Comic Magazines'},
        {name: 'Fan Clubs & Zines'},
        {name: 'Merchandise & Memorabilia'},
        {name: 'Comic Book Supplies & Accessories'},
        {name: 'Other Comic Books & Memorabilia'}
    ]},
    {name: 'Decorative', parent: 'Collectables', sub: [
        {name: 'Ashtrays'},
        {name: 'AntiBasketsque'},
        {name: 'Bells'},
        {name: 'Bird Houses'},
        {name: 'Book Ends'},
        {name: 'Bottles'},
        {name: 'Boxes, Jars & Tins'},
        {name: 'Candles'},
        {name: 'Candle Holders'},
        {name: 'Decorative Clocks'},
        {name: 'Collectable Spoons'},
        {name: 'Collector Plates'},
        {name: 'Decorative Fans'},
        {name: 'Decorative Armour & Shields'},
        {name: 'Flue Covers'},
        {name: 'Frames'},
        {name: 'Incense Burners'},
        {name: 'Masks'},
        {name: 'Music Boxes'},
        {name: 'Paperweights'},
        {name: 'Pins'},
        {name: 'Plaques & Signs'},
        {name: 'Planters'},
        {name: 'Posters & Prints'},
        {name: 'Sculptures & Figurines'},
        {name: 'Suncatchers & Mobiles'},
        {name: 'Tiles'},
        {name: 'Urns'},
        {name: 'Vases'},
        {name: 'Other Decorative Collectables'}
    ]},
    {name: 'Film Memoribilia', parent: 'Collectables', sub: [
        {name: 'Ads & Flyers'},
        {name: 'Film Autographs'},
        {name: 'Film Badges'},
        {name: 'Bags & Rucksacks'},
        {name: 'Bookmarks'},
        {name: 'Calendars'},
        {name: 'Clippings'},
        {name: 'Clothing'},
        {name: 'Figures & Dolls'},
        {name: 'Film Cells'},
        {name: 'Fridge Magnets'},
        {name: 'Keyrings'},
        {name: 'Lobby Cards'},
        {name: 'Mouse Mats'},
        {name: 'Mugs'},
        {name: 'Novelties'},
        {name: 'Photographs'},
        {name: 'Plates'},
        {name: 'Film Playing Cards'},
        {name: 'Film Postcards'},
        {name: 'Posters'},
        {name: 'Pressbooks & Press Kits'},
        {name: 'Programmes & Brochures'},
        {name: 'Promotional Items'},
        {name: 'Set Props'},
        {name: 'Scripts'},
        {name: 'Standees & Banners'},
        {name: 'Film Wardrobe'},
        {name: 'Other Film Memorabilia'}
    ]},
    {name: 'Militaria', parent: 'Collectables', sub: [
        {name: 'Ancient & Medieval (Pre-1500)'},
        {name: 'Early Modern (1500-1800)'},
        {name: '19th Century (1800-1899)'},
        {name: 'Boer War (1899-1902'},
        {name: '1903-1913'},
        {name: 'World War I (1914-1918)'},
        {name: 'Inter-War (1919-1938)'},
        {name: 'World War II (1939-1945)'},
        {name: '1946-1960'},
        {name: 'Vietnam War (1961-1975)'},
        {name: '1976-1981'},
        {name: 'Falklands War (1982)'},
        {name: '1983-1989'},
        {name: 'Gulf War (1990-1991)'},
        {name: 'Current Militaria (1991-Present)'},
        {name: 'Surplus & Equipment'},
        {name: 'Other Militaria'}
    ]},
    {name: 'Model Trains', parent: 'Collectables', sub: [
        {name: 'Railroads & Trains'},
        {name: 'Power & Control'},
        {name: 'Storage & Display'},
        {name: 'Books & Guides'},
        {name: 'Model Train Mixed Lots'}
    ]},
    {name: 'Postcards', parent: 'Collectables', sub: [
        {name: 'Postcards & Supplies'},
        {name: 'Postcard Accessories'}
    ]},
    {name: 'Pottery', parent: 'Collectables', sub: [
        {name: 'Cookware, Dinnerware & Serveware'},
        {name: 'Decorative Pottery & Glassware'},
        {name: 'Drinkware & Barware'},
        {name: 'Lamps & Lighting'},
        {name: 'Other Pottery & Glass'}
    ]},
    {name: 'Sci-Fi', parent: 'Collectables', sub: [
        {name: 'Science Fiction'},
        {name: 'Alien'},
        {name: 'Babylon 5'},
        {name: 'Battlestar Galactica'},
        {name: "Blake's Seven"},
        {name: 'Captain Scarlet'},
        {name: 'Doctor Who'},
        {name: 'Farscape'},
        {name: 'Godzilla'},
        {name: 'Outer Limits'},
        {name: 'Planet Of The Apes'},
        {name: 'Red Dwarf'},
        {name: 'Space 1999'},
        {name: 'Stargate'},
        {name: 'Star Trek'},
        {name: 'Star Wars'},
        {name: 'Thunderbirds'},
        {name: 'X-Files'},
        {name: 'Other Sci-Fi Collectables'}
    ]},
    {name: 'Sports Memoribilia', parent: 'Collectables', attributes:['brand_sports'], sub: [
        {name: 'American Football Memorabilia'},
        {name: 'Boxing Memorabilia'},
        {name: 'Cricket Memorabilia'},
        {name: 'Football Memorabilia'},
        {name: 'Football Programmes'},
        {name: 'Famous Football Shirts'},
        {name: 'Golf Memorabilia'},
        {name: 'Horse Racing Memorabilia'},
        {name: 'Ice Hockey Memorabilia'},
        {name: 'Motor Sport Memorabilia'},
        {name: 'Other Sports Memorabilia'},
        {name: 'Olympic Memorabilia'},
        {name: 'Rugby Memorabilia'},
        {name: 'Sports Stickers, Collections & Albums'},
        {name: 'Sports Trading Cards'},
        {name: 'Stubbeto'},
        {name: 'Tennis Memorabilia'},
        {name: 'Wrestling Memorabilia'}
    ]},
    {name: 'Stamps', parent: 'Collectables', sub: [
        {name: 'Africa'},
        {name: 'Asia'},
        {name: 'Australia & Oceania'},
        {name: 'British Colonies & Territories'},
        {name: 'Caribbean'},
        {name: 'Central & South America'},
        {name: 'Europe'},
        {name: 'Great Britain'},
        {name: 'Ireland'},
        {name: 'Middle East'},
        {name: 'North America'},
        {name: 'Other Stamps'},
        {name: 'Philately'},
        {name: 'Publications & Supplies'},
        {name: 'Thematics'},
        {name: 'United States'},
        {name: 'Worldwide'}
    ]},
    {name: 'Trading Cards & Collectable Card Games', parent: 'Collectables', sub: [
        {name: 'Individual Cards'},
        {name: 'Sealed Packs'},
        {name: 'Sealed Boxes'},
        {name: 'Sealed Cases'},
        {name: 'Sealed Decks & Kits'},
        {name: "CCG NFT's"},
        {name: 'Box & Case Breaks'},
        {name: 'Player Built Decks'},
        {name: 'Sets'},
        {name: 'Mixed Card Lots'},
        {name: 'Uncut Sheets'},
        {name: 'CCG Supplies & Accessories'},
        {name: 'Other CCG Items'}
    ]},
    {name: 'Transportation', parent: 'Collectables', sub: [
        {name: 'Aeronautica'},
        {name: 'Agricultural & Industrial'},
        {name: 'Automobilia'},
        {name: 'Bicycle'},
        {name: 'Bus & Coach'},
        {name: 'Motocycle & Scooter'},
        {name: 'Nautical'},
        {name: 'Railwayana'},
        {name: 'Tramway & Light Rail'},
        {name: 'Trucks, Lorries & Vans'},
        {name: 'Underground'},
        {name: 'Other Transportation'},
    ]}
]

module.exports = categories;